### ISSUE TITLE
EPG

### ISSUE THREAD

**Issue by Trozmagon** [Rampaigh/AutoIPTV#3]
More of a question than an issue. Do you have a matching EPG source or some advice on where to source/build one? BTW thanks for this repo ;).

**Comment by viniciusolima12** [comment]
Trozmagon, sorry but i'll not help you, could you answer this for me?....does it works for you? how do you use it? I tryied on kodi and android and both had 10 seconds issue..

**Comment by Rampaigh** [comment]
Hello,

The EPG is still in progress and will be implemented in the future shortly...

For the Android to work well: https://autoiptv.net/pages/setup/#iosandroid
Check this out. The reason for it to stop after 10 second could be that the player that you are using might not have a loop function in it to reconnect the stream when it disconnects?

Also VLC Media Player does a great job at keeping the stream alive when it disconnects, because it has a loop function that just reconnect once it has disconnected: https://autoiptv.net/pages/setup/#vlc

Please let me know if this helps?

**Comment by Trozmagon** [comment]
Thanks mate. Once you have the EPG complete send me a message and I'll write you up a Tvheadend implementation guide.

**Comment by Rampaigh** [comment]
Awesome... I'll let you know, also keep an eye on the Repo, incase I forget...
